config/routes.rb
TaskManager::Application.routes.draw do
  get "users/profile"
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users
  get "welcome/index"

  resources :events do
    resources :tasks, only: [:index, :new, :create]
  end

  resources :tasks, only: [] do
    patch :assign, on: :member
  end

  resources :categories
  resources :admin
  
  

  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can [:read, :create], Event
    can [:update, :destroy], Event, owner: user
  end
end



    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/bryanrite/cancancan/wiki/Defining-Abilities

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :tasks
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :category, class_name: Category
  has_many   :tasks

  validates :name, length: { in: 4..30 }
  #validates :category, presence: true

  accepts_nested_attributes_for :tasks, allow_destroy: true

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user_id, class_name: User
  belongs_to :event
  validates :name, :description, presence: true
  validates_length_of :description,
    :minimum   => 5,
    :maximum   => 50000,
    :too_short => "minimum is 10 symbols",
    :too_long  => "maximum is 500 symbols"
end

app/models/user.rb
class User < ActiveRecord::Base
	#before_create :create_role
	#ROLES = %w[admin user]
  #def role?(base_role)
  #ROLES.index(base_role.to_s) <= ROLES.index(role)
  #end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         validates :password, confirmation: true
    #private
     # def create_role
     #   self.roles << Role.find_by_name(:user)
      #end
      has_many :events, foreign_key: :category_id
      has_many :tasks, foreign_key: :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception 
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  load_resource param_method: :event_params

  def index
    @events = Event.includes(:category)
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = current_user.events.new(event_params)
    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to events_path
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  private
    
    def event_params
      params.require(:event).permit(:name, tasks_attributes: task_params)
    end

    def task_params
      [:id, :description, :deadline, :_destroy, :user_id, :name]
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_event, except: [:find]
    #def discontinue
    # authorize! :discontinue, @task
    #end
    def assign
    @task = Task.find(params[:id])
    @task.update_column(:user_id, current_user.id)
    redirect_to event_tasks_path(@task.event)
    end

    def index
      @tasks = @event.tasks
    end

    def new
      @task = Task.new
    end

    def create
     @task = @event.tasks.new(task_params)
       if @task.save
         redirect_to event_tasks_path(@event)
       else
         render :new
       end
    end
       
    def show
    end
        
    def edit
    end

    def update
        if @task.update(task_params)
          redirect_to @task
        else 
          render 'edit'
        end
    end

    def destroy
      @task.destroy
      redirect_to tasks_path
    end

    private

      def find_event
        @event = Event.find(params[:event_id])
      end
      def task_params
        params.require(:task).permit(:name, :description, :category, :priority, :deadline)
      end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :check_permissions, :only => [:new, :create, :cancel]
  skip_before_filter :require_no_authentication

    #def check_permissions
     #   authorize! :create, resource
    #end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end
 
 
  def resource
    @resource ||= User.new
  end
 
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= simple_nested_form_for @event do |f| %>
  <%= f.input :name %>
  <%= f.association :category %>

  <%= f.fields_for :tasks do |task_form| %>
    <% if task_form.object.new_record? %>
      <%= task_form.input :name %>
      <%= task_form.input :description, as: :text %>
      <%= task_form.input :deadline %>
      <%= task_form.input :priority %>
      <%= task_form.link_to_remove "Delete" %>
    <% end %>
  <% end %>
  <p><%= f.link_to_add "Make new task", :tasks %></p>
  <%= f.submit %>
<% end %>
<br><%=link_to_function "Back", "history.back()" %></br>

app/views/events/edit.html.erb
<%= render 'form' %>

app/views/events/index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th><%= Event.human_attribute_name(:name) %></th>
      <th><%= Event.human_attribute_name(:category) %></th>
      <th>You can</th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |p| %>
      <tr>
        <td><%= link_to p.name, event_path(p) %></td>
        <td><%= p.category %></td>
        <td>
            <b><%= link_to 'Edit', edit_event_path(p) %></b>  or   

            <b><%= link_to 'delete', event_path(p), method: :delete, data: { confirm: 'Seriously?' } %></b>
            <br>and view
            <b><%= link_to 'tasks', event_tasks_path(p) %></b> for current event</br>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Create new event', new_event_path, class: 'btn' %>
<br><%=link_to_function "Back", "history.back()" %></br>

app/views/events/new.html.erb
<%= render 'form' %>

app/views/events/show.html.erb
<h1> Event </h1>
<b><%= @event.name %></b>
<p><%= @category %></p>
<%= simple_nested_form_for @event do |f| %>
 
  <%= f.fields_for :tasks do |task_form| %>
    <% if task_form.object.new_record? %>
      <%= task_form.input :name %>
      <%= task_form.input :description, as: :text %>
      <%= task_form.input :deadline %>
      <%= task_form.input :priority %>
      <%= task_form.link_to_remove "Delete" %>
    <% end %>
  <% end %>
  <p><%= f.link_to_add "Make new task", :tasks %></p>
  <%= f.submit %>
<h1> Tasks </h1>
<table class='table'>
	<th>Name</th>
	<th>Description</th>
	<th>Deadline</th>
  <% @event.tasks.each do |task| %>
    <tr>
      <td><%= task.name %></td>
      <td><%= task.description %></td>
      <td><%= task.deadline %></td>
      <td><%= task.user_id %></td>
      <td><%= task.priority %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'My Events', events_path %>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Daybook" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <%= render "shared/links" %>
            <ul class="nav nav-list">
              <li class="nav-header"></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p align="right">&copy; G-man 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/shared/_links.html.erb
<ul>
  <% if user_signed_in? %>
    <li><%= link_to "My Profile", edit_user_registration_path%> </li>
    <li><%= link_to "Exit", destroy_user_session_path, :method => :DELETE %> </li>
    <li><%= link_to 'Homepage', welcome_index_path %></li>
  <% else %>
    <li><%= link_to "Registration", new_user_registration_path%> </li>
    <li><%= link_to "Enter", new_user_session_path%> </li>
    <li><%= link_to 'Homepage', welcome_index_path %></li>
  <% end %>
</ul>   

app/views/tasks/edit.html.erb
<h1>Editing task</h1>
 
<%= simple_form_for :task, url: task_path(@task), method: :patch do |f| %>
  <% if @task.errors.any? %>
  <div id="azaza  error  azazaz">
    <h2><%= pluralize(@task.errors.count, "error") %> prohibited
        this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :text %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :test %><br>
    <%= f.text_area :description %>
  </p>
 
 <div class="form-actions">
  <button type="submit" class="btn btn-primary">Save</button>
  <button type="button" class="btn">Cancel</button>
</div>
<% end %>
 
<%= link_to 'Go back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Tasklist</h1>



 
<table>
  <table class="table">
    <table class="table table-bordered">
  <tr>
    <th>Active Tasks</th>
  </tr>
 
   
  <% @tasks.each do |task| %>
    <tr>
      <td><%= task.name %></td>
      <td><%= task.description %></td>
      <% if can? :read, task %>
      <td><%= link_to 'Show', task %></td>
      <% end %>
      <% if can? :update, task %>
      <td><%= link_to 'Edit', edit_task_path(task) %></td>
      <% end %>
      <% if can? :destroy, task %>
      <td><%= link_to 'Delete', task_path(task),
        method: :delete, data: { confirm: 'Tu uveren?' } %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/tasks/new.html.erb
<%= simple_form_for Task.new, html: {class: 'form-horizontal' }, url: tasks_path do |f| %>      
  <%= f.input :name %>
  <%= f.input :time_in %>
  <%= f.input :time_out %>
  <%= f.input :description %>
  <%= f.association :category %>
  <%= f.input :priority %>

  <div class="form-actions">
  <button type="submit" class="btn btn-primary">Save</button>
  <button type="button" class="btn">Cancel</button>
</div>
<% end %>
<%= link_to 'Go back', tasks_path %>

app/views/tasks/show.html.erb
<p>
	
  <strong>Title:</strong>
  <%= @task.name %>
</p>
 
 <p>
  <strong>Description:</strong>
  <br>
  <%= @task.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @task.category %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>Time_in:</strong>
  <%= @task.time_in %>
</p>

<p>
  <strong>Time_out:</strong>
  <%= @task.time_out %>
</p>

<%= link_to 'Go back', tasks_path %>    or    <%= link_to 'Edit', edit_task_path(@task) %>

app/views/users/_form.html.erb
<%= f.collection_select :role, User::ROLES, :to_s, :humanize %>

app/views/users/profile.html.erb
<h1>Users#profile</h1>
<p>Find me in app/views/users/profile.html.erb</p>

app/views/welcome/index.html.erb
<center>
  <p>Task-manager/organizer v. 0.0.2</p>
  <h1><%= link_to "Daybook", controller: "events" %></h1>
    <% if user_signed_in? %>
      <span>Hi, <%= current_user.email %></span>
      <%= link_to 'Exit', destroy_user_session_path, :method => :DELETE %>
    <% else %>
  <p>Enter or register</p>
</center>
<% end %>